initial_state: 'on'
alias: 'Weather notification'
trigger:
  - platform: time_pattern
    minutes: '/5'
    seconds: '50'
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
  - condition: template
    value_template: "{{ states('sensor.dark_sky_temperature') != 'unknown' }}"
action:
  - service: notify.lm_notify
    data_template:
      message: >-
        {% if states('sensor.dark_sky_temperature') != 'unknown' %}
          {{ states('sensor.dark_sky_temperature')|round(0) }}C outside and {{ states('sensor.dark_sky_minutely_summary')|lower }} {{ states('sensor.dark_sky_hourly_summary') }}
        {% else %}
          {{ states.weather.dark_sky.attributes.forecast[0].temperature }}C outside and {{ states.weather.dark_sky.attributes.forecast[0].condition }}
        {% endif %}
        {% if (not is_state('sensor.dark_sky_alerts','0')) and (states('sensor.dark_sky_alerts') != "unknown") %} There are weather alerts {% endif %}
  - service: notify.logfile
    data_template:
      message: >-
        {% if states('sensor.dark_sky_temperature') != 'unknown' %}
          SENDLIVING {{ states('sensor.dark_sky_temperature')|round(0) }}C outside and {{ states('sensor.dark_sky_minutely_summary')|lower }} {{ states('sensor.dark_sky_hourly_summary') }}
        {% else %}
          SENDLIVING {{ states.weather.dark_sky.attributes.forecast[0].temperature }}C outside and {{ states.weather.dark_sky.attributes.forecast[0].condition }}
        {% endif %}
        {% if (not is_state('sensor.dark_sky_alerts','0')) and (states('sensor.dark_sky_alerts') != "unknown") %} There are weather alerts {% endif %}
