initial_state: 'off'
alias: 'cooler outside (livingroom)'
trigger:
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_temperature
    above: 23
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 22
  - platform: template
    value_template: >
      {{ states('sensor.dark_sky_temperature')|int < states('sensor.pi3_living_room_multi_temperature')|int }}
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.pi3_living_room_multi_temperature
    above: 23
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 22
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 5
  - condition: template
    value_template: >
      {{ states('sensor.dark_sky_temperature')|int < states('sensor.pi3_living_room_multi_temperature')|int }}
  - condition: state
    entity_id: binary_sensor.patio_window_left
    state: 'off'
  - condition: state
    entity_id: binary_sensor.patio_window_right
    state: 'off'
  - condition: state
    entity_id: binary_sensor.pi3_patio_door_left_sensor
    state: 'off'
  - condition: template
    value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('script.automation.cooler_outside_livingroom','last_triggered'))|float)|float > 1800 }}"
action:
  - service: tts.google_cloud_say
    entity_id: media_player.living_room_display
    data_template:
      message: "It's now cooler outside than inside, you should open some windows or doors."
  - service: automation.turn_off
    entity_id: automation.cooler_outside_livingroom
  - wait_template: "{{ is_state('media_player.living_room_display','playing') }}"
  - wait_template: "{{ is_state('media_player.living_room_display','idle') }}"
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room_display
