initial_state: 'on'
alias: 'Hotter outside (livingroom)'
trigger:
  - platform: state
    entity_id: binary_sensor.patio_window_left
    to: 'on'
  - platform: state
    entity_id: binary_sensor.patio_window_right
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pi3_patio_door_left_sensor
    to: 'on'
  - platform: template
    value_template: >
      {{ 
        states('sensor.dark_sky_temperature')|int > 23
          and
        ( states('sensor.dark_sky_temperature')|int > states('sensor.pi3_living_room_multi_temperature')|int )
      }}
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 23
  - condition: template
    value_template: >
      {{ states('sensor.dark_sky_temperature')|int > states('sensor.pi3_living_room_multi_temperature')|int }}
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.patio_window_left
      state: 'on'
    - condition: state
      entity_id: binary_sensor.patio_window_right
      state: 'on'
    - condition: state
      entity_id: binary_sensor.pi3_patio_door_left_sensor
      state: 'on'
  # Been at least 30 minutes
  - condition: template
    value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('script.automation.hotter_outside_livingroom','last_triggered'))|float)|float > 1800 }}"
action:
  - service: tts.google_cloud_say
    entity_id: media_player.living_room_display
    data_template:
      message: "It's now hotter outside than inside, you should close the windows and doors."
  - service: automation.turn_on
    entity_id: automation.cooler_outside_livingroom
