alias: 'Utility door open after sunset turn off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.pi3_utility_door_exterior_sensor
    to: 'off'
  - platform: state
    entity_id: binary_sensor.pi3_patio_door_left_sensor
    to: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.sun_elevation
      below: -4
    - condition: state
      entity_id: switch.pi3_garden_lights_switch
      state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.pi3_garden_lights_switch
