- id: '1572606895884'
  alias: A New Automation
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == states(''input_datetime.ha_shutdown'')|as_timestamp()|timestamp_custom(''%H:%M'')  }}'
  condition: []
  action:
  - data: {}
    entity_id: light.yeelight_strip1_286c07afc307
    service: light.turn_off
