- id: '1572606895884'
  alias: A New Automation
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == states(''input_datetime.ha_shutdown'')|as_timestamp()|timestamp_custom(''%H:%M'')  }}'
  condition: []
  action:
  - data:
      message: This is a test
    service: notify.person2_telegram
