homeassistant:
  # Name of the location where Home Assistant is running
  name: Our home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /data/homeassistant
    - /home/homeassistant/maps

logger:
  default: info

default_config:

config:

frontend: !include frontend.yaml
map:
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    lovelace-people:
      mode: yaml
      filename: ui-lovelace-people.yaml
      title: People
      icon: mdi:account-group
      show_in_sidebar: true
      require_admin: false
    lovelace-admin:
      mode: yaml
      filename: ui-lovelace-admin.yaml
      title: Admin
      icon: mdi:view-carousel
      show_in_sidebar: true
      require_admin: true
    lovelace-automations:
      mode: yaml
      filename: ui-lovelace-automations.yaml
      title: Automations
      icon: mdi:robot
      show_in_sidebar: true
      require_admin: true

http: !include http.yaml

discovery: 

history:
logbook:
recorder: !include recorder.yaml
influxdb: !include influxdb.yaml

tts: !include tts.yaml

group: !include_dir_named groups/

script: !include_dir_named scripts/
automation: !include automations.yaml
automation mine: !include_dir_list automation/
scene: !include scenes.yaml
scene mine: !include_dir_list scenes/

 
device_tracker: !include_dir_list device_tracker/
proximity: !include_dir_merge_named proximity/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
google: !include google.yaml
sun:
weather: !include_dir_merge_list weather/
zone: !include zones.yaml

input_number: !include_dir_named input_number/
input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_text: !include_dir_named input_text/
timer: !include_dir_named timers/

light: !include_dir_merge_list light/
switch: !include_dir_merge_list switch/
samsungtv: !include samsung_tv.yaml
rest_command: !include_dir_named rest_command/

alarm_control_panel: !include_dir_list alarm/

alert: !include_dir_named alerts/
notify: !include_dir_merge_list notify/
telegram_bot: !include telegram.yaml

camera: !include_dir_list camera/
ffmpeg: !include ffmpeg.yaml
stream:

image_processing: !include_dir_list image_processing/

mqtt: !include mqtt.yaml

circadian_lighting: !include circadian.yaml
remote_homeassistant: !include remote_ha.yaml
