title: Our Home
custom_header: !include lovelace/custom_header.yaml
views:
  - !include lovelace/view-overview.yaml
  - !include lovelace/view-floorplan.yaml
  - !include lovelace/view-floor-ground.yaml
  - !include lovelace/view-floor-first.yaml
  - !include lovelace/view-map.yaml
  - !include lovelace/view-surveillance.yaml
  - !include lovelace/view-spacer2.yaml
  - !include lovelace/view-train_status.yaml
  - !include lovelace/view-media.yaml
  - !include lovelace/view-people.yaml
  - !include lovelace/view-information.yaml
  - !include lovelace/view-devices.yaml
  - !include lovelace/view-inputs.yaml
  - !include lovelace/view-spacer.yaml
  - !include lovelace/view-automations.yaml
  - !include lovelace/view-automations_bedrooms.yaml
  - !include lovelace/view-automations_person2.yaml
  - !include lovelace/view-automations_person3.yaml
  - !include lovelace/view-automations_person1.yaml
  - !include lovelace/view-automations_group.yaml
  - !include lovelace/view-automations_more.yaml
  - !include lovelace/view-automations_notifications.yaml
  - !include lovelace/view-scripts.yaml
  - !include lovelace/view-cast.yaml
