alias: 'person1 Alarm Playing'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.person1
    to: 'playing'
  - platform: state
    entity_id: media_player.person1
    to: 'idle'
  - platform: state
    entity_id: media_player.cast_second_bedroom_speaker
    to: 'playing'
  - platform: state
    entity_id: media_player.cast_second_bedroom_speaker
    to: 'idle'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.person1_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.person1_in_bed
      state: 'on'
    - condition: time
      after: '04:00:00'
      before: '12:00:00'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_alarm_sounded
  - service: notify.logfile
    data_template:
      message: >
        Turned on person1 alarm playing because the {{ trigger.to_state.name }} was {{ trigger.to_state.state }} at {{ now() }}
