initial_state: 'on'
alias: 'Battery ER14250'
trigger:
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_garage_closed_bike, sensor.pi3_zwave_battery_garage_closed_bike
    below: 25
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_garage_closed_bike, sensor.pi3_zwave_battery_garage_closed_bike
    below: 10
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_garage_closed_bike, sensor.pi3_zwave_battery_garage_closed_bike
    below: 5
    for:
      minutes: 5
action:
  service: notify.logfile
  data_template:
    message: "SENDME The {{ trigger.to_state.name }} is at {{ trigger.to_state.state }}% battery, it uses a ER14250 battery"
