initial_state: 'on'
alias: 'Battery Sensative'
trigger:
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_utility_door_exterior, sensor.pi3_zwave_battery_patio_door_left, sensor.pi3_zwave_battery_front_door
    below: 25
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_utility_door_exterior, sensor.pi3_zwave_battery_patio_door_left, sensor.pi3_zwave_battery_front_door
    below: 10
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_zwave_battery_utility_door_exterior, sensor.pi3_zwave_battery_patio_door_left, sensor.pi3_zwave_battery_front_door
    below: 5
    for:
      minutes: 5
action:
  service: notify.logfile
  data_template:
    message: "SENDME The {{ trigger.to_state.name }} is at {{ trigger.to_state.state }}% battery, buy a replacement soon"
