initial_state: 'on'
alias: 'Front camera motion stream off'
trigger:
  - platform: state
    entity_id: input_boolean.front_camera_motion_interesting
    to: 'on'
    for: '00:01:00'
action:
  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.stream_camera
      - input_boolean.front_camera_motion_interesting
      
