initial_state: 'on'
alias: 'Motion hook'
trigger:
  - platform: webhook
    webhook_id: !secret slack_pi3
action:
  - service: notify.logfile
    data_template:
      message: >
        Motion detection by {{ trigger.webhook_id }}  
  - service: input_boolean.turn_on
    entity_id: input_boolean.front_camera_motion
