initial_state: 'on'
alias: 'Hall mode Night on'
trigger:
  - platform: state
    entity_id: binary_sensor.hall_downstairs_occupancy
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.sun_elevation
    below: 5
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 15
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.hall_downstairs_illuminance
    below: 10
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
  - platform: state
    entity_id:
      - input_boolean.living_room_occupied
      - input_boolean.family_room_occupied
    to: 'on'
  - platform: state
    to: 'Just Arrived'
    entity_id: 
      - input_select.person2_status_dropdown
      - input_select.person3_status_dropdown
      - input_select.person1_status_dropdown
      - input_select.person4_status_dropdown
  - platform: state
    entity_id: binary_sensor.pi3_front_door_sensor
    to: 'on'
condition:
  - condition: and
    conditions:
    # Dark in the living room
    - condition: numeric_state
      entity_id: sensor.pi3_living_room_multi_luminance
      below: 25
    # Sun is relatively low
    - condition: numeric_state
      entity_id: sensor.sun_elevation
      below: 15
    # Dark in the hall
    - condition: numeric_state
      entity_id: sensor.hall_downstairs_illuminance
      below: 10
    - condition: or
      conditions:
    # We're not away
      - condition: state
        entity_id: input_boolean.home_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{{ states('input_select.hall') in ('Away','Off','Auto') }}"
      # We're awake
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
action:
  - service: notify.logfile
    data_template:
      message: "Turned the hall light to Night On because of {{ trigger.to_state.entity_id }}, was {{ states('input_select.hall') }}"
  - service: input_select.select_option
    data:
      entity_id: input_select.hall
      option: 'Night on'
