initial_state: 'on'
alias: 'Living room not occupied'
trigger:
  - platform: state
    entity_id: media_player.samsung_tv
    to: 'off'
    for: '00:01:00'
  - platform: state
    entity_id: media_player.samsung_tv
    to: 'off'
    for: '00:05:00'
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
    to: 'not_home'
    for: '00:01:00'
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'unavailable'
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'unavailable'
    for: '00:05:00'
  - platform: state
    entity_id: media_player.living_room
    to: 'paused'
    for: '00:03:00'
  - platform: state
    entity_id: media_player.living_room
    to: 'idle'
    for: '00:03:00'
  - platform: state
    entity_id: binary_sensor.pi3_living_room_motion
    to: 'off'
    for: '00:01:00'
condition:
  - condition: and
    conditions:
    # Room must currently be occupied
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'on'
    # Requires all the media devices to be off, paused, unavailable, etc
    - condition: state
      entity_id: media_player.samsung_tv
      state: 'off'
    - condition: state
      entity_id: device_tracker.livingroom_chromecast
      state: 'not_home'
    - condition: state
      entity_id: media_player.cast_living_room_tv
      state: 'unavailable'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.living_room
        state: 'paused'
      - condition: state
        entity_id: media_player.living_room
        state: 'idle'
    # And no motion
    - condition: state
      entity_id: binary_sensor.pi3_living_room_motion
      state: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.living_room_occupied
