- platform: openweathermap
  api_key: !secret openweather_api_key
  forecast: true
  monitored_conditions:
  - weather
  - temperature
  - wind_speed
  - wind_bearing
  - humidity
  - pressure
  - clouds
  - rain
  - snow
  - weather_code
