initial_state: 'on'
alias: 'Hotter outside (office)'
trigger:
  - platform: state
    entity_id: binary_sensor.office_window
    to: 'on'
  - platform: template
    value_template: >
      {{ 
        states('sensor.dark_sky_temperature')|int > 23
          and
        ( states('sensor.dark_sky_temperature')|int > sensor.pi3_office_multi_temperature )
      }}
condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.office_window
      state: 'on'
action:
  - service: tts.google_cloud_say
    entity_id: media_player.office_smart_display
    data_template:
      message: "It's now hotter outside than inside, you should close the window."
