initial_state: 'on'
alias: 'Hotter outside (office)'
trigger:
  - platform: state
    entity_id: binary_sensor.office_window
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 23
  - platform: template
    value_template: >
      {{ states('sensor.dark_sky_temperature')|int > states('sensor.pi3_office_multi_temperature')|int }}
condition:
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 23
  - condition: template
    value_template: >
      {{ states('sensor.dark_sky_temperature')|int > states('sensor.pi3_office_multi_temperature')|int }}
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.office_window
      state: 'on'
action:
  - service: tts.google_cloud_say
    entity_id: media_player.office_smart_display
    data_template:
      message: "It's now hotter outside than inside, you should close the window."
