initial_state: 'off'
alias: 'Zigbee router online'
trigger:
  - platform: state
    entity_id: binary_sensor.zigbee2mqtt_router_1
    to: 'on'
    for:
      minutes: 1
condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.hall
      state: 'on'
    - condition: state
      entity_id: light.hall
      state: 'off'
  - condition: state
    entity_id: binary_sensor.zigbee2mqtt_router_1
    state: 'on'
action:
  - service: notify.person2_telegram
    data_template:
      message: >-
        The Zigbee router and lights are alive again
  - service: homeassistant.turn_off
    entity_id: automation.zigbee_router_online
